# Generated by Django 4.0.2 on 2022-03-29 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='itemcatalog',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('itemname', models.CharField(max_length=100)),
                ('itemtype', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('image', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='orderhistory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField()),
                ('item_id', models.IntegerField()),
                ('username', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
