# Generated by Django 4.0.2 on 2022-04-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
